version: 2

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    target-branch: staging
    open-pull-requests-limit: 5
    groups:
      minor-and-patch-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    target-branch: staging
    open-pull-requests-limit: 5
    groups:
      github-actions-updates:
        patterns:
          - "*"
